API_keys:
  OpenAI: "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"
  Replicate: "r8-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  Anthropic: "sk-ant-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  Mistral: "sk-mis-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  hf_token: "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"